# Generated by Django 6.0.2 on 2026-04-26 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_studentprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='likes',
        ),
        migrations.AddField(
            model_name='material',
            name='file_size',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='storage_limit',
            field=models.BigIntegerField(default=104857600),
        ),
    ]
